services:
  boilerplate-database:
    image: postgres
    container_name: boilerplate-database
    volumes:
      - boilerplate_data:/var/lib/postgresql/boilerplate-data/
    environment:
      - "POSTGRES_USER=boilerplate"
      - "POSTGRES_PASSWORD=boilerplate"
      - "POSTGRES_DB=BoilerPlate"
    ports:
      - "5432:5432"

volumes:
  boilerplate_data:
