name: Lint and Test

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.12
          enable-cache: true
      - name: Signal if cache restored
        if: steps.setup-uv.outputs.cache-hit == 'true'
        run: echo "Cache was restored"
      - name: Run linter
        run: uv run ruff check

  tests:
    needs: linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.12
          enable-cache: true
      - name: Signal if cache restored
        if: steps.setup-uv.outputs.cache-hit == 'true'
        run: echo "Cache was restored"
      - name: Run tests
        run: uv run pytest
